# -*- coding: utf-8 -*-
"""api_key.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pz5DW5l0kgdPeOcKzqoYPRm5JoH5Airc
"""

api_key = "AIzaSyDMaW_FR2ji0u0O_WUE3KllfNYf8SzgSno"